apiVersion: v1
kind: Service
metadata:
  name: result
  labels:
    name: result-app-service
    app: demo-voting-app
spec:
  type: NodePort
  port:
     -port: 80
      targetPort: 80
      nodePort: 3005
  selector:
      name: result-app-pod
      app: demo-voting-app
